### ISSUE TITLE
changes to agent-bootstrapper.jar

### ISSUE THREAD

**Issue by jamielennox1** [unibet/puppet-go#8]
Module Version: v0.4.0

agent-bootstrapper.jar now requires that the first parameter (-serverUrl) now has "https://" at the beginning and "/go" at the end. This is currently breaking your code in gocd v16.8.0.

This line is currently in: templates/go-agent-sh.erb line 80.
Also, I don't think you can't append <%= @name %>-running at the end of this process. It seems to error unless it's taken out.

**Comment by jlyheden** [comment]
Thx for the report, I will have a look at patching it so that go-agent-sh.erb will be both forward and backwards compatible. However not a huge fan of having to maintain these kind of changes in the puppet module, maybe in a new major release of this module I will investigate if possible to reuse the start scripts provided by Thoughtworks installation packages rather than pushing out bastardised snapshotted versions of them.

**Comment by jamielennox1** [comment]
I agree. Maybe replicating the process in the go.cd documentation will reduce this overhead. Here's the link: https://docs.go.cd/16.8.0/advanced_usage/admin_install_multiple_agents.html#linux-rpm-and-deb.

I've had my change merged for the code at the bottom of this page. It shouldn't be:
java -jar /usr/share/go-agent/agent-bootstrapper.jar 127.0.0.1 &
instead it should be:
java -jar /usr/share/go-agent/agent-bootstrapper.jar -serverUrl https://127.0.0.1/go &

**Comment by jlyheden** [comment]
Cool, I'll have a look at that!

Pushed the suggested fix for now to branch feature/fix-for-issue-8, have just tested it in vagrant Centos but please verify in your environment.

**Comment by jlyheden** [comment]
Released version 0.4.1 that fixes this issue
